### ISSUE TITLE
Add function removeROIs from OMERO 

### ISSUE THREAD

**Issue by romainGuiet** [GReD-Clermont/omero_macro-extensions#9]
Hi @ppouchin ,

THANK YOU for sharing this tool! It's exartly what we're looking for and I found it thanks ot [your recent post on imagej.sc](https://forum.image.sc/t/imagej-omero-plugin-not-connecting-to-demo-openmicroscopy-site/64693/2)

Using your template I was quickly able to run a macro and add ROIs on my image in OMERO.
The issue is that ROIs are pilling up, so a removeROIs function could be necessary to avoid tedious work of removing them manually.

Cheers,

Romain

**Comment by ppouchin** [comment]
Hi @romainGuiet,

Thank you for your feedback!

I must confess it never bothered me much because I installed [a script](https://github.com/ppouchin/omero-user-scripts/blob/master/util_scripts/Remove_ROIs.py) on our server to let users delete all the ROIs from the OMERO interface.

But it is indeed a missing function from these extensions, and I will gladly add it, especially considering you've opened up a PR!

**Comment by ppouchin** [comment]
You might also be interested in [this other plugin](https://github.com/GReD-Clermont/omero_batch-plugin) which batch processes images with a macro or script.
This other tool automatically opens images and saves results after running even the most simple script such as:
`run("Z Project...", "projection=[Max Intensity] all");`

**Comment by ppouchin** [comment]
Closed with #10
